version: '3'
services:
  web:
    build: 
      context: .
      args:
        YOUR_ENV: development
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app/manage.py", "runserver", "0.0.0.0:8000"]
    volumes: 
     - .:/code
    ports:
     - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword