# Generated by Django 5.0.3 on 2024-03-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_alter_transaction_profile_alter_transactiontag_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='profile',
            new_name='user',
        ),
    ]
